name: access-intake-utils
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python==3.10
  - jsonschema
  - pooch
  - pre-commit
  - pytest
  - pip
  - coverage
  - intake-esm
  - mypy
  - numpy
  - ruff
  - tabulate
  - xarray
  - pip:
    - codecov